# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
#relative_permalinks: true

# Setup
title:            Dr. Anne-Sophie Fleckenstein
tagline:          'Dr. Anne-Sophie Fleckenstein'
description:      'Website'
baseurl: "/dr-anne-sophie-fleckenstein/" # the subpath of your site, e.g. /blog
url: "https://juliafleckenstein.github.io/" # the base hostname & protocol for your site, e.g. http://example.com

paginate:         5

# Custom vars
#version:          2.1.0

github:
  repo:           https://juliafleckenstein.github.io/dr-anne-sophie-fleckenstein/

plugins:
  - jekyll-feed

collections:
  sessions:
    output: true
